### ISSUE TITLE
Is there any branch for 2-4-stable

### ISSUE THREAD

**Issue by arthurtalkgoal** [spree-contrib/spree-multi-domain#111]
Hi,

Does the gem support 2-4-stable? or any one developing it?

Thanks,

**Comment by nimashariatian** [comment]
+1. this needs to be upgraded to 2.4 so that we can finalize our spree + rails upgrade!
thanks!

**Comment by futhr** [comment]
Now you have a `2-4-stable` branch based on current `master` that used Spree v2.4.0.beta.
