### ISSUE TITLE
Error undefined method `logo_file_name' for #<Spree::Store:0x007f8c1de55eb0>

### ISSUE THREAD

**Issue by alanalvespi** [spree-contrib/spree-multi-domain#117]
I got this error when running the migrations. Appreciate feedback

**Comment by virajrch** [comment]
Hi, I just came across this problem too. Have you got any solution yet?

Thanks

**Comment by alanalvespi** [comment]
Hi @virajrch , I solved it.

Looks like for some reason 'logo_file_name' wasn't in the db schema. What I did it was to drop and create my database, then execute bundle exec rails g spree_multi_domain:install and finally run migrations. 

That solved my issue. Hope it helps to you as well.

**Comment by virajrch** [comment]
Hi alanalvespi,

Thanks for the reply. Unfortunately it doesn't work for me. Even if I drop and create the db and run `bundle exec rails g spree_multi_domain:install` it gives the same error. Apparently it is throwing the exception from 'create_store_from_preferences' migration file which is in spree gem not multi_domain.

Any help will be appreciated.

Thanks

**Comment by virajrch** [comment]
I uninstalled gem. Ran migrations and then installed multi_domain. It worked. :)
