### ISSUE TITLE
Spree 3.0 Update

### ISSUE THREAD

**Issue by jspizziri** [spree-contrib/spree-multi-domain#121]
Will there be an update for spree 3.0 (which has just recently has been released)?

**Comment by JDutil** [comment]
If people still using this extension provide pull requests updating it I'll review for being merged, but this extension is no longer officially maintained.

**Comment by jspizziri** [comment]
Thanks for the quick response. If this extension is no longer maintained is there another you could recommend that is.

Also, I'm not opposed to contributing; however given my current schedule it may make sense just to stick with 2.4. Depending what happens in the next few months I may try and submit a PR.

Thanks again!

**Comment by JDutil** [comment]
This is still the best one to use, but most of it's functionality has become part of spree core now making this less relevant.

**Comment by jspizziri** [comment]
Sorry, just for clarification, what functionality are you speaking of exactly? And is that documented anywhere?

Does the core now have the ability to have layouts and products relative to a store?

**Comment by JDutil** [comment]
The models and things making you able to have different stores per domain is now in core.  As well as the ability to have certain products per store, but we still haven't updated the admin panel allow store management.  This extension may carry on if people want to continue using it for the different layouts/templates per store, but the admin side of things is planned to be added to the normal backend.

**Comment by jspizziri** [comment]
I don't have a problem working on a 3.0 branch, I just want to know that its not going to become obsolete in a few months due to updates to the spree core; so forgive me for trying to get up to speed on this.

I definitely see the ability to have multiple stores. However currently, spree master doesn't seem to have anything localizing products to a given store. Am I to understand that that is for sure coming and just hasn't been built yet, or is there something I'm missing?

Similarly, if spree core is being built to deal with multiple stores and their related products, wouldn't it necessarily need to have the ability to differentiate layouts per store? It seems as though multiple stores would be a moot point with no layout adaptations, as it's effectively the same store at multiple URL's, which could be accomplished by a simple URL redirect.

**Comment by JDutil** [comment]
Well the frontend aspects of this i.e. different templates per store will probably remain here.  

Improving the backend store management should be built into the main spree_backend in the future so porting what's in this repo over to there and stripping this down to just handling the frontend is what I envision for this extension going forward.  That being said I don't have plans to do this work myself in the near future so if that is something you'd like to contribute that would be great.

The general use case we're worrying about is similar to Surfdome's setup where they want to display different locale, currency, and default country settings etc.. per store by domain, but they aren't worried about changing the layout.  For instance see:
https://www.surfdome.us/
https://www.surfdome.fr/
