### ISSUE TITLE
How do I view the frontend of a non default domain on localhost?

### ISSUE THREAD

**Issue by acreilly** [spree-contrib/spree-multi-domain#129]
The answer is probably right in front of me but, how do I view the frontend of a non default domain on localhost?

**Comment by dpritchett** [comment]
@acreilly have you tried setting up new domains via `/etc/hosts` and then connecting to those domains in the browser rather than connecting to `http://localhost:3000`.

```
127.0.0.1 primary-spree-host.com     
127.0.0.1 secondary-spree-host.com
```

**Comment by jsheng08** [comment]
I use localhost:3000 as my default and sg.localhost:3000 as my secondary. It works.

**Comment by JDutil** [comment]
I typically use http://pow.cx/ to run dev environments. The other answers above work as well. Essentially you just need a named dns to resolve to localhost.
