### ISSUE TITLE
can't install dev env with spree 3.1.0

### ISSUE THREAD

**Issue by delblues** [spree-contrib/spree-multi-domain#151]
I'm following the instructions to install, I put the line

> gem 'spree-multi-domain', github: 'spree-contrib/spree-multi-domain', branch: '3-1-stable'

at the gemfile (my spree version is 3-1-0 as well), but I cant get install and keeping having the message: 

> Could not find gem 'spree-multi-domain' in git://github.com/spree-contrib/spree-multi-domain.git (at 3-1-stable@5017b56). Source does not contain any versions of 'spree-multi-domain' 

having the same issue with the master branch,

Somebody knows what is happening?
Tks

**Comment by damianlegawiec** [comment]
@delblues thanks for submitting this issue. It should be:

```
gem 'spree_multi_domain', github: 'spree-contrib/spree-multi-domain', branch: '3-1-stable'
```

README.md updated with proper instructions

**Comment by delblues** [comment]
@damianlegawiec thanks, now it worked!
