### ISSUE TITLE
ResourceController (NameError)

### ISSUE THREAD

**Issue by anandshrivastavatech** [spree-contrib/spree-multi-domain#197]
I am getting the "uninitialized constant ResourceController (NameError)" while running the installer command.

  * spree (3.7.0)
  * spree_api (3.7.0)
  * spree_auth_devise (3.5.0)
  * spree_backend (3.7.0)
  * spree_cmd (3.7.0)
  * spree_core (3.7.0)
  * spree_extension (0.0.9)
  * spree_frontend (3.7.0)
  * spree_gateway (3.4.1)
  * spree_multi_domain (3.0.5)
  * spree_sample (3.7.0)

**Comment by anandshrivastavatech** [comment]
Resolved.

**Comment by damianlegawiec** [comment]
@anandshrivastavatech would you mind sharing how did you resolve this issue?

**Comment by dani07** [comment]
@anandshrivastavatech @damianlegawiec  Im also facing the same issue. Any help would be appreciated.

- spree (4.1.9)
- spree_gateway (3.8.0)
- spree_multi_domain (3.0.5)
- spree_auth_devise (4.2.0)
