### ISSUE TITLE
How can i use Spree-multi-domain with Spree 4.1.12?

### ISSUE THREAD

**Issue by lcsmachado** [spree-contrib/spree-multi-domain#235]
Is there a way of using spree-multi-domain with spree 4.1.12?
Today i get these errors:

Running bundle install: 
  Bundler could not find compatible versions for gem "spree":
    In snapshot (Gemfile.lock):
      spree (= 4.1.12)
  
    In Gemfile:
      spree (= 4.1.12)
  
      spree_multi_domain was resolved to 4.0.0, which depends on
        spree (>= 4.2.0.rc4, < 5.0)
  
  Running `bundle update` will rebuild your snapshot from scratch, using only
  the gems in your Gemfile, which may resolve the conflict.

and:
  Running bundle update:
    Bundler could not find compatible versions for gem "spree":
      In Gemfile:
        spree (= 4.1.12)
    
        spree_multi_domain was resolved to 4.0.0, which depends on
          spree (>= 4.2.0.rc4, < 5.0)

**Comment by damianlegawiec** [comment]
You need to upgrade to Spree 4.2 - https://guides.spreecommerce.org/developer/upgrades/four-dot-one-to-four-dot-two.html
